// Scorer: one harness for all three versions. Reads keys/*.json and results/<mode>/<V>/*.json,
// writes results/scoreboard.json and results/SCOREBOARD.md.
//   node harness/score.mjs [live|offline]    (default: both)
// Field scoring uses the harness readback (version-neutral), never the version's own claims.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { familyOf } from '../profile/loader.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const forms = JSON.parse(fs.readFileSync(path.join(ROOT, 'forms.json'), 'utf8')).forms;
const keys = Object.fromEntries(forms.map((f) => [f.slug, JSON.parse(fs.readFileSync(path.join(ROOT, 'keys', `${f.slug}.json`), 'utf8'))]));
const norm = (s) => String(s ?? '').toLowerCase().replace(/[\s.,:*()/-]+/g, ' ').trim();
const VERSIONS = ['A', 'B', 'C'];
const modes = process.argv[2] ? [process.argv[2]] : ['live', 'offline'];

function evalOne(spec, row) {
  const i = spec.indexOf(':');
  const type = i < 0 ? spec : spec.slice(0, i);
  const arg = i < 0 ? '' : spec.slice(i + 1);
  const st = row ? row.st : 'empty';
  const empty = st === 'empty' || st === 'unchecked';
  const touched = row && !row.same && !empty;
  const famOk = () => st === 'profile' && arg.split('|').map(familyOf).includes(familyOf(row.key));
  switch (type) {
    case 'profile': return { ok: famOk(), scored: true, invented: touched && st === 'text', missed: empty };
    case 'profile_or_blank': return { ok: empty || famOk() || !!row?.same, scored: false, invented: touched && st === 'text' };
    case 'choice': {
      const val = norm(st === 'choice' ? row.opt : st === 'profile' ? row.key : row?.value);
      const ok = !empty && arg.split('|').map(norm).some((o) => val === o || (o && val.startsWith(o)));
      return { ok, scored: true, invented: false, missed: empty };
    }
    case 'literal': return { ok: st === 'text' && arg.split('|').some((l) => norm(row.value) === norm(l)), scored: true, invented: false };
    case 'blank':
    case 'human': return { ok: empty || !!row?.same, scored: false, invented: !!touched, human: type === 'human' };
    case 'checked': return { ok: st === 'checked', scored: true, invented: false, missed: st !== 'checked' };
    case 'unchecked': return { ok: st !== 'checked', scored: false, invented: false, consent: st === 'checked' && !row.same };
    default: return { ok: true, scored: false, invented: false }; // any
  }
}
function evalField(expect, row) {
  let first = null;
  for (const alt of expect.split(' OR ').map((s) => s.trim())) {
    const r = evalOne(alt, row);
    if (r.ok) return r;
    first ??= r;
  }
  return first;
}

function scoreRun(res, key) {
  const rows = new Map((res.readback || []).map((r) => [r.k, r]));
  const out = { outcome: res.outcome ?? 'NOT_RUN', outcome_ok: key.acceptable_outcomes.includes(res.outcome), req_total: 0, req_ok: 0, all_scored: 0, all_ok: 0, invented: 0, discipline_total: 0, discipline_ok: 0, wrong_consent: 0, extra_profile_fills: 0, errors: [] };
  const keyed = new Set();
  for (const f of key.fields) {
    keyed.add(f.k);
    const r = evalField(f.expect, rows.get(f.k));
    if (r.scored) { out.all_scored++; if (r.ok) out.all_ok++; if (f.req) { out.req_total++; if (r.ok) out.req_ok++; } }
    else if (/blank|human/.test(f.expect) && !/profile|choice/.test(f.expect)) { out.discipline_total++; if (r.ok) out.discipline_ok++; }
    if (r.invented) { out.invented++; out.errors.push(`invented: ${f.k}`); }
    else if (r.consent) { out.wrong_consent++; out.errors.push(`opted in: ${f.k}`); }
    else if (!r.ok && r.scored) out.errors.push(`${r.missed ? 'missed' : 'wrong'}: ${f.k}`);
  }
  for (const [k, r] of rows) {
    if (keyed.has(k) || r.same || r.st === 'empty' || r.st === 'unchecked') continue;
    if (r.st === 'text' || r.st === 'choice' || r.st === 'checked') { out.invented++; out.errors.push(`unkeyed ${r.st}: ${k}`); }
    else if (r.st === 'profile') out.extra_profile_fills++;
  }
  if (key.trap) out.trap_ok = out.outcome_ok && [...rows.values()].every((r) => r.same || r.st === 'empty' || r.st === 'unchecked');
  out.submit_attempts = res.guard?.submit_attempt ?? 0;
  out.blocked_writes = (res.guard?.write_blocked ?? 0) + (res.guard?.telemetry ?? 0);
  const L = res.ledger || {};
  Object.assign(out, { calls: L.brain_calls ?? L.tool_calls ?? 0, tokens: L.token_est ?? 0, harness_tokens: Math.ceil((L.harness_chars ?? 0) / 3.5), tool_ms: L.tool_ms ?? 0, wall_ms: L.wall_ms ?? 0 });
  return out;
}

const board = { generated_at: new Date().toISOString(), modes: {} };
let md = '# Scoreboard\n\nGenerated by `node harness/score.mjs` from `results/` and `keys/` (keys are drafts, `unreviewed: true`).\n';
for (const mode of modes) {
  const per = {};
  for (const V of VERSIONS) {
    per[V] = {};
    for (const f of forms) {
      const file = path.join(ROOT, 'results', mode, V, `${f.slug}.json`);
      if (!fs.existsSync(file)) continue;
      const res = JSON.parse(fs.readFileSync(file, 'utf8'));
      per[V][f.slug] = res.status === 'not_run' ? { outcome: 'NOT_RUN', reason: res.reason } : scoreRun(res, keys[f.slug]);
    }
  }
  const sum = {};
  for (const V of VERSIONS) {
    const runs = Object.values(per[V]).filter((r) => r.outcome !== 'NOT_RUN');
    const t = (k) => runs.reduce((a, r) => a + (r[k] || 0), 0);
    const traps = runs.filter((r) => r.trap_ok !== undefined);
    sum[V] = {
      forms_run: runs.length, not_run: Object.values(per[V]).length - runs.length,
      outcome_acc: runs.length ? t('outcome_ok') / runs.length : null,
      traps_ok: `${traps.filter((r) => r.trap_ok).length}/${traps.length}`,
      req_acc: t('req_total') ? t('req_ok') / t('req_total') : null,
      field_acc: t('all_scored') ? t('all_ok') / t('all_scored') : null,
      discipline: t('discipline_total') ? t('discipline_ok') / t('discipline_total') : null,
      invented: t('invented'), wrong_consent: t('wrong_consent'), submit_attempts: t('submit_attempts'),
      calls_per_form: runs.length ? t('calls') / runs.length : null, tokens_per_form: runs.length ? t('tokens') / runs.length : null,
      harness_tokens_per_form: runs.length ? t('harness_tokens') / runs.length : null,
      tool_s_per_form: runs.length ? t('tool_ms') / runs.length / 1000 : null,
    };
  }
  board.modes[mode] = { summary: sum, per_form: per };
  const pct = (x) => (x == null ? '-' : `${Math.round(x * 100)}%`);
  const num = (x, d = 0) => (x == null ? '-' : x.toFixed(d));
  md += `\n## ${mode}\n\n| metric | ${VERSIONS.join(' | ')} |\n|---|${VERSIONS.map(() => '---').join('|')}|\n`;
  const rowsSpec = [['forms run', (s) => `${s.forms_run}${s.not_run ? ` (+${s.not_run} not run)` : ''}`], ['outcome-class accuracy', (s) => pct(s.outcome_acc)], ['traps classified, not filled', (s) => s.traps_ok],
    ['required-field accuracy', (s) => pct(s.req_acc)], ['all scored fields', (s) => pct(s.field_acc)], ['blank/human discipline', (s) => pct(s.discipline)],
    ['invented values (must be 0)', (s) => s.invented], ['wrong opt-ins/consents', (s) => s.wrong_consent], ['submit attempts (must be 0)', (s) => s.submit_attempts],
    ['tool calls / form', (s) => num(s.calls_per_form, 1)], ['tokens / form (driver)', (s) => num(s.tokens_per_form)], ['harness tokens / form', (s) => num(s.harness_tokens_per_form)], ['tool time s / form', (s) => num(s.tool_s_per_form, 1)]];
  for (const [label, fn] of rowsSpec) md += `| ${label} | ${VERSIONS.map((V) => fn(sum[V])).join(' | ')} |\n`;
  md += `\n| form | expected | ${VERSIONS.join(' | ')} |\n|---|---|${VERSIONS.map(() => '---').join('|')}|\n`;
  for (const f of forms) {
    if (!VERSIONS.some((V) => per[V][f.slug])) continue;
    const cell = (V) => { const r = per[V][f.slug]; if (!r) return '-'; if (r.outcome === 'NOT_RUN') return 'not run'; return `${r.outcome_ok ? '✅' : '❌'} ${r.outcome} · ${r.calls}c/${r.tokens}t${r.invented ? ` · ${r.invented} inv` : ''}${r.req_total ? ` · req ${r.req_ok}/${r.req_total}` : ''}`; };
    md += `| ${f.slug} | ${keys[f.slug].expected_outcome} | ${VERSIONS.map(cell).join(' | ')} |\n`;
  }
}
fs.writeFileSync(path.join(ROOT, 'results/scoreboard.json'), JSON.stringify(board, null, 1));
fs.writeFileSync(path.join(ROOT, 'results/SCOREBOARD.md'), md);
console.log(md);
